# print("Hello World!")
# print("Hello Again")
# print("I like typing this!"  )
# print("This is fun")
# print('Yay! Printing')
# print("I'd much rather you 'not'")
# print('I "said" do not touch this')
print(' I want to make money using Python 2 or 3')